r_L = zeros(eltype(u0), size(u0))
r_H = zeros(eltype(u0), size(u0))
a = zeros(eltype(x), blending_length)
θ = zeros(eltype(x), blending_length)
r_entropy_rhs = zeros(eltype(x), size(x))
v = zeros(eltype(u0), size(u0))
Rdr = zeros(eltype(u0), blending_length)
Dv = zeros(eltype(u0), blending_length)